version: 2
updates:
- package-ecosystem: npm
  directory: "/node-ovhook"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/electron-overlay"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
